// What the rule-based fallback would say for the SAME Friday scenario.
// Generated by porting the Python `_fallback` logic to TypeScript using
// the same inputs. This is what Aiman gets if GLM is removed.
// NOTE: The rules engine has NO platform awareness — it cannot do arbitrage.

import type { ShiftRecommendation } from "./types";

export const ruleBasedRecommendation: ShiftRecommendation = {
  recommendation: "partial",
  shift_windows: [
    { start: "11:00", end: "14:00", zones: ["PJ", "Damansara"], target_app: "Grab", opportunity_gain_rm: 0.0 },
    { start: "18:00", end: "22:00", zones: ["Bangsar"], target_app: "Grab", opportunity_gain_rm: 0.0 },
  ],
  projected_net_rm: 105.5,
  projected_gross_rm: 137.15,
  projected_petrol_rm: 15.83,
  confidence: "low",
  reasoning_narrative:
    "Recent 7-day average is RM106 net, weather shows multiple rainy hours, and it's a weekday — recommending a partial day. Standard split shift between lunch (PJ/Damansara) and dinner (Bangsar) blocks based on rider's general historical pattern.",
  key_factors: [
    {
      factor: "7-day average",
      impact: "positive",
      weight: "medium",
      note: "Above the RM70 work threshold.",
    },
    {
      factor: "Weather (rough)",
      impact: "neutral",
      weight: "low",
      note: "9 hours flagged as rainy; threshold of 8 not exceeded enough to recommend rest.",
    },
  ],
  caveats: ["Rule-based output. No event awareness. No incentive awareness. No platform arbitrage."],
  source: "fallback_rules",
};

// What's MISSING from the rule-based output that GLM caught.
// This goes in the comparison view to make the gap explicit.
export const glmAdvantages = [
  {
    category: "Platform Arbitrage (Switch Window)",
    rules: "No cross-platform awareness. Tells rider to stay on Grab all day, missing the ShopeeFood +RM4 flash voucher entirely.",
    glm: "Spots the ShopeeFood +RM4 flash incentive in Bangsar (12-3pm) and creates a Switch Window: switch to ShopeeFood at 12pm, then back to Grab at 3pm. +30% hourly earnings during that window.",
  },
  {
    category: "Live promo comparison",
    rules: "Ignores all three platform incentives (ShopeeFood, Grab boost, FoodPanda).",
    glm: "Compares ShopeeFood +RM4 vs Grab 1.2x vs FoodPanda (none), calculates which platform wins per time slot, and assigns target_app per shift window.",
  },
  {
    category: "Event awareness",
    rules: "Ignores KL Grand Prix entirely.",
    glm: "Identifies Bukit Jalil crowd spillover into Bangsar; weights it as positive medium signal for evening demand.",
  },
  {
    category: "Personalised history",
    rules: "Uses 7-day average only.",
    glm: "Cites the rider's specific Friday 15:00 PJ rain-pattern (RM11 avg) to justify skipping that slot.",
  },
  {
    category: "Confidence calibration",
    rules: "Always 'low' — fixed.",
    glm: "Returns 'high' because the ShopeeFood voucher creates a clear, actionable Switch Window with strong upside.",
  },
  {
    category: "Plain-language explanation",
    rules: "Generic 2-sentence template.",
    glm: "5-sentence narrative explaining exactly when to switch apps, why, and how much extra they'll earn — in Malaysian rider speak.",
  },
];