// What the rule-based fallback would say for the SAME Friday scenario.
// Generated by porting the Python `_fallback` logic to TypeScript using
// the same inputs. This is what Aiman gets if GLM is removed.

import type { ShiftRecommendation } from "./types";

export const ruleBasedRecommendation: ShiftRecommendation = {
  recommendation: "partial",
  shift_windows: [
    { start: "11:00", end: "14:00", zones: ["PJ", "Damansara"] },
    { start: "18:00", end: "22:00", zones: ["Bangsar"] },
  ],
  projected_net_rm: 105.5,
  projected_gross_rm: 137.15,
  projected_petrol_rm: 15.83,
  confidence: "low",
  reasoning_narrative:
    "Recent 7-day average is RM106 net, weather shows multiple rainy hours, and it's a weekday — recommending a partial day. Standard split shift between lunch (PJ/Damansara) and dinner (Bangsar) blocks based on rider's general historical pattern.",
  key_factors: [
    {
      factor: "7-day average",
      impact: "positive",
      weight: "medium",
      note: "Above the RM70 work threshold.",
    },
    {
      factor: "Weather (rough)",
      impact: "neutral",
      weight: "low",
      note: "9 hours flagged as rainy; threshold of 8 not exceeded enough to recommend rest.",
    },
  ],
  caveats: ["Rule-based output. No event awareness. No incentive awareness."],
  source: "fallback_rules",
};

// What's MISSING from the rule-based output that GLM caught.
// This goes in the comparison view to make the gap explicit.
export const glmAdvantages = [
  {
    category: "Event awareness",
    rules: "Ignores KL Grand Prix entirely.",
    glm: "Identifies Bukit Jalil crowd spillover into Bangsar; weights it as positive medium signal.",
  },
  {
    category: "Incentive reasoning",
    rules: "Ignores +RM2 Bangsar bonus zone.",
    glm: "Anchors evening shift to Bangsar 18:00-22:00 specifically because of the RM2/order incentive.",
  },
  {
    category: "Personalised history",
    rules: "Uses 7-day average only.",
    glm: "Cites the rider's specific Friday 15:00 PJ rain-pattern (RM11 avg) to justify skipping that slot.",
  },
  {
    category: "Confidence calibration",
    rules: "Always 'low' — fixed.",
    glm: "Returns 'medium' because signals point the same direction with one risk (rain intensity).",
  },
  {
    category: "Plain-language explanation",
    rules: "Generic 2-sentence template.",
    glm: "5-sentence narrative tailored to today's specific tradeoffs in Malaysian rider speak.",
  },
];